project:
  type: website

website:
  title: "Shivesh Krishna | Data-Driven Insights"
  navbar:
    left:
      - text: "Home"
        href: about.qmd
      - text: "Blog"
        href: index.qmd
      - icon: github
        href: https://github.com/shiveshkrishna
      - icon: twitter
        href: https://twitter.com/shiveshkrishna
format:
  html:
    theme: lumen
    css: styles.css
