project:
  type: website

website:
  title: "Shivesh Krishna - Data Insights Blog"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/shiveshkrishna
      - icon: twitter
        href: https://twitter.com/yourtwitterhandle

format:
  html:
    theme: lumen
    css: styles.css
